- name: install kafka
  ansible.builtin.yum:
    name: kafka-server
    state: latest

- name: Configure kafka server.properties
  ansible.builtin.template:
    src: server.properties.j2
    dest: "/etc/kafka/conf/server.properties"
  notify:
    - Restart kafka

- name: Enable Kafka
  ansible.builtin.systemd:
    name: kafka-server
    state: restarted
    enabled: yes
